# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: STAGE_INSTALL_NODE
    displayName: install node
    jobs:
      - job: JOB_INIT
        displayName: init
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'
  - template: ./stage-initialize.yml
  - stage: STAGE_BUILD
    displayName: build
    jobs:
      - job: BUILD
        steps:
          - template: ./steps-node-install
          - script: |
              npx nx run build
            displayName: build Nx
