steps:
  - script: |
      echo "node version: $(node -v)"
      echo "npm version: $(npm -v)"
      echo "yarn version: $(yarn -v)"
      echo $NODE_OPTIONS
    displayName: 'Display Versions'
  - task: Cache@2
    inputs:
      key: 'yarn | "$(Agent.OS)" | yarn.lock'
      path: $(System.DefaultWorkingDirectory)/node_modules
      cacheHitVar: YARN_CACHE_RESTORED
    displayName: Cache Yarn packages
  - ${{ if eq(parameters.installCypress, true) }}:
      - script: |
          yarn install --ignore-engines --frozen-lockfile
        displayName: 'Install Dependencies (With Cypress)'
        condition: ne(variables['YARN_CACHE_RESTORED'], 'true')
